server:
  port: 9080
  context-path: /api-a

spring:
  profiles:
    include: mybatis
  thymeleaf:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

security:
  basic:
    enabled: false
  ignored: /css/**,/js/**,/images/**,/**/favicon.ico,/webjars/**

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
