server:
  port: 9080
  context-path: /api-auth

spring:
  profiles:
    include: mybatis
  thymeleaf:
    cache: false

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
