server:
  port: 8082
  context-path: /scr-f

spring:
  profiles:
    include: mybatis,security
  freemarker:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
