server:
  port: 8081
  context-path: /fmk

spring:
  profiles:
    include: default,mybatis,security
  freemarker:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
