logging:
  level:
    org.mybatis: DEBUG

mybatis:
  config: classpath:META-INF/mybatis/mybatis-config.xml

spring:
  datasource:
    tomcat:
      max-active: 3
      url: jdbc:h2:tcp://localhost:10001/~/db/spring-boot-multi-sample;LOCK_TIMEOUT=10000;
      username: sa
      password:

