logging:
  level:
    org.mybatis: DEBUG

mybatis:
  type-aliases-package: com.github.kazuki43zoo.sample.domain.model, com.github.kazuki43zoo.sample.domain.repository
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    default-fetch-size: 100

spring:
  datasource:
#    driver-class-name: org.h2.Driver
    tomcat:
      url: jdbc:h2:tcp://localhost:10001/~/db/spring-boot-multi-sample;LOCK_TIMEOUT=10000;
      username: sa
      password:
      max-active: 3
      initial-size: ${spring.datasource.tomcat.max-active}
      min-idle: ${spring.datasource.tomcat.max-active}
      max-idle: ${spring.datasource.tomcat.max-active}

