server:
  port: 8083

spring:
  profiles:
    include: default,mybatis
  freemarker:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
