server:
  port: 9081
  context-path: /api

spring:
  profiles:
    include: default,mybatis
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      indent_output: true
    deserialization:
      fail_on_unknown_properties: false

api:
  error:
    documentation-url: http://example.com/api/errors
    message-mappings:
      ? org.springframework.http.converter.HttpMessageNotReadableException
      : Request body is invalid
      ? org.springframework.web.bind.MethodArgumentNotValidException
      : Request value is invalid
      ? org.springframework.validation.BindException
      : Request value is invalid
      ? org.springframework.security.access.AccessDeniedException
      : Access is denied

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG

security:
  oauth2:
    client:
      client-id: sample-resource
      client-secret: password
    resource:
      jwt:
        key-uri: http://localhost:9080/api-auth/oauth/token_key

