server:
  port: 8082
  context-path: /jsp
  error:
    whitelabel:
      enabled: false # disable default error view

spring:
  profiles:
    include: default,mybatis,security
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
