server:
  port: 8080
  context-path: /tlf

spring:
  profiles:
    include: default,mybatis,security
  thymeleaf:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

logging:
  level:
    com.github.kazuki43zoo.sample: DEBUG
